objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>It is used to store the department for an employee.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Used to define the employees for a Department</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>The address of the employee.</description>
    <inlineHelpText>The address of the employee.</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Employee__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Employee date of birth.</description>
    <inlineHelpText>Employee date of birth.</inlineHelpText>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference fora Department Object.</description>
    <inlineHelpText>Reference fora Department Object.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee email address.</description>
    <inlineHelpText>Employee email address.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of the employee (M or F).</description>
    <inlineHelpText>Gender of the employee (M or F).</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Employee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Employee telephone number.</description>
    <inlineHelpText>Employee telephone number.</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

classes/EmployeeController.cls
/**********************************************************************************************************
 @Class Name               : EmployeeController.cls
 @Description              : Apex Controller to get Employee details in order to create the PDF file and attaching to it
 @Author                   : Stefan Stancioiu 
 @Group                    :
 @Last Modified By         : Stefan Stancioiu 
 @Last Modified On         : 21/03/2020, 10:00:00 AM
 @Modification Log         : 21/03/2020, 10:00:00 AM
 ==========================================================================================
 Ver           Date              Author                               Modification
 ==========================================================================================
 1.0           22/03/2020        Stefan Stancioiu                     Initial Version
**********************************************************************************************************/

public with sharing class EmployeeController {

    public Employee__c emp { get; set; } 

    //constructor
	public EmployeeController() {
    	emp = [SELECT Id, Name, Department__c, Email__c, Address__c, Gender__c, Phone__c, Date_of_Birth__c, Department__r.Name
               FROM Employee__c 
               LIMIT 1];
    }
}