objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>It is used to store the department for an employee.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Department__c/fields/Admin_R_Dept__c.field-meta.xml
<CustomField>
    <fullName>Admin_R_Dept__c</fullName>
    <description>The department (DEPTNO) to which this department reports; the department at the highest level reports to itself.</description>
    <inlineHelpText>The department (DEPTNO) to which this department reports; the department at the highest level reports to itself.</inlineHelpText>
    <label>Admin R Dept</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Department__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the department.</description>
    <inlineHelpText>Location of the department.</inlineHelpText>
    <label>Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Department__c/fields/Manager_No__c.field-meta.xml
<CustomField>
    <fullName>Manager_No__c</fullName>
    <description>Employee number (EMPNO) of the department manager.</description>
    <inlineHelpText>Employee number (EMPNO) of the department manager.</inlineHelpText>
    <label>Manager No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/UnitTestHelperDepartment.cls
/**********************************************************************************************************
 @Class Name               : UnitTestHelperDepartment.cls
 @Description              : Test Util methods for Department
 @Author                   : Stefan Stancioiu 
 @Group                    :
 @Last Modified By         : Stefan Stancioiu 
 @Last Modified On         : 21/03/2020, 10:00:00 AM
 @Modification Log         : 21/03/2020, 10:00:00 AM
 ==========================================================================================
 Ver           Date              Author                               Modification
 ==========================================================================================
 1.0           21/03/2020        Stefan Stancioiu                     Initial Version
**********************************************************************************************************/
@isTest(SeeAllData=true)
public with sharing class UnitTestHelperDepartment {
    
    /*********************************************************************************
      Method Name    : createDepartment
      Author         : Stefan Stancioiu, March 21rd 2020
      Description    : method to create Department__c record
      Return Type    : Department__c
      Parameter      :
      *********************************************************************************/
    public static Department__c createDepartment() {
        Department__c dep = new Department__c();
        dep.Name = 'Test Department';
        dep.Admin_R_Dept__c = '01';
        dep.Location__c = 'Location 1';
        dep.Manager_No__c = '02';
        return dep;
    }
}