objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>It is used to store the department for an employee.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Used to define the employees for a Department</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>The address of the employee.</description>
    <inlineHelpText>The address of the employee.</inlineHelpText>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference fora Department Object.</description>
    <inlineHelpText>Reference fora Department Object.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee email address.</description>
    <inlineHelpText>Employee email address.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender of the employee (M or F).</description>
    <inlineHelpText>Gender of the employee (M or F).</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/UnitTestHelperEmployee.cls
/**********************************************************************************************************
 @Class Name               : UnitTestHelperEmployee.cls
 @Description              : Test Util methods for Employee
 @Author                   : Stefan Stancioiu 
 @Group                    :
 @Last Modified By         : Stefan Stancioiu 
 @Last Modified On         : 21/03/2020, 10:00:00 AM
 @Modification Log         : 21/03/2020, 10:00:00 AM
 ==========================================================================================
 Ver           Date              Author                               Modification
 ==========================================================================================
 1.0           21/03/2020        Stefan Stancioiu                     Initial Version
**********************************************************************************************************/
@isTest(SeeAllData=true)
public  with sharing class UnitTestHelperEmployee {
    
    /*********************************************************************************
      Method Name    : createEmployee
      Author         : Stefan Stancioiu, March 21rd 2020
      Description    : method to create Employee record
      Return Type    : Employee__C
      Parameter      :
      *********************************************************************************/
    public static Employee__C createEmployee(Id departmentId) {
        Employee__C emp = new Employee__C();
        emp.Department__c = departmentId;
        emp.Address__c = 'Test Address';
        emp.Email__c = 'test.email@test.com';
        emp.Gender__c = 'Male';
        return emp;
    }
}