objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>It is used to store the department for an employee.</description>
    <label>Department</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Department__c/fields/Admin_R_Dept__c.field-meta.xml
<CustomField>
    <fullName>Admin_R_Dept__c</fullName>
    <description>The department (DEPTNO) to which this department reports; the department at the highest level reports to itself.</description>
    <inlineHelpText>The department (DEPTNO) to which this department reports; the department at the highest level reports to itself.</inlineHelpText>
    <label>Admin R Dept</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Department__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the department.</description>
    <inlineHelpText>Location of the department.</inlineHelpText>
    <label>Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Department__c/fields/Manager_No__c.field-meta.xml
<CustomField>
    <fullName>Manager_No__c</fullName>
    <description>Employee number (EMPNO) of the department manager.</description>
    <inlineHelpText>Employee number (EMPNO) of the department manager.</inlineHelpText>
    <label>Manager No</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/ManageDepartmentsController.cls
/**********************************************************************************************************
 @Class Name               : ManageDepartmentsController.cls
 @Description              : Apex class used as controller for getting Departments in Visualforce page
 @Author                   : Stefan Stancioiu 
 @Group                    :
 @Last Modified By         : Stefan Stancioiu 
 @Last Modified On         : 21/03/2020, 10:00:00 AM
 @Modification Log         : 21/03/2020, 10:00:00 AM
 ==========================================================================================
 Ver           Date              Author                               Modification
 ==========================================================================================
 1.0           22/03/2020        Stefan Stancioiu                     Initial Version
**********************************************************************************************************/

public class ManageDepartmentsController {

	// used to pass the list with Departments records
    public List<Department__c> departments { get; set; }
  
    // used to get a hold of the department record selected for deletion
    public string selectedDepId { get; set; }
  
   	public ManageDepartmentsController() {
        // load records into the DataTable
        loadData();
   	}
  
    private void loadData() {
        departments = [SELECT Id, Name, Location__c, Admin_R_Dept__c, Manager_No__c FROM Department__c LIMIT 100];
    }
    
    public void editDepartment() {
        // if for any reason we are missing the reference 
    	if (selectedDepId == null) {
            return;
      	}
        // find the department record within the collection
      	Department__c toBeEdited = null;
        for(Department__c d : departments) {
            if(d.Id == selectedDepId) {
          		toBeEdited = d;
          		break;
            }
        }
        // if department record found delete it
        if (toBeEdited != null) {
            update toBeEdited;
        }
        loadData();
    }
  
    public void deleteDepartment() {
       
        // if for any reason we are missing the reference 
    	if (selectedDepId == null) {
            return;
      	}
     
      	// find the department record within the collection
      	Department__c tobeDeleted = null;
      	for(Department__c d : departments)
       		if (d.Id == selectedDepId) {
          		tobeDeleted = d;
          		break;
       	}
      
      	// if department record found delete it
      	if (tobeDeleted != null) {
       		delete tobeDeleted;
      	}
     
      	// refresh the list with data
      	loadData();
   	}    
}